/**
 * EWMA control chart on standardized values.
 *
 * References: Roberts (1959); Lucas & Saccucci, Technometrics 1990 (ARL design);
 * Neubauer, Clin Chem 1997;43:594–601 (EWMA for clinical QC; squared-deviation EWMA
 * for imprecision).
 *
 * E_t = λ z_t + (1−λ) E_{t−1},  E_0 = 0.
 * Exact time-varying limits: ± L·sqrt( λ/(2−λ) · (1 − (1−λ)^{2t}) ).
 *
 * Defaults λ = 0.2, L = 2.962 → ARL0 ≈ 500 (Lucas–Saccucci design; verified by Monte
 * Carlo in this repo at ≈496). Alternative "more sensitive to small shifts":
 * λ = 0.1, L = 2.814 (ARL0 ≈ 486; detects a 1σ shift within 15 runs ~91% of the time).
 * NOTE: the pairing (λ=0.2, L=2.86) sometimes quoted for ARL0 500 actually yields
 * ARL0 ≈ 368 by simulation; we use the calibrated constants and document this in
 * docs/validation.md.
 *
 * Variance EWMA (Neubauer-style): V_t = λ z_t² + (1−λ) V_{t−1}, V_0 = 1, one-sided upper
 * limit. The limit is Monte-Carlo calibrated for ARL0 ≈ 500 in tools/reference and the
 * calibration is a committed fixture (see `varianceEwmaLimit`).
 *
 * Assumes independent, approximately normal z; autocorrelation inflates false alarms.
 */

export interface EwmaOptions {
  lambda?: number; // default 0.2
  L?: number; // default 2.962 (ARL0 ≈ 500)
}

/** Monte-Carlo-verified (λ, L) pairs for ARL0 ≈ 500 with exact time-varying limits. */
export const EWMA_PRESETS = {
  default: { lambda: 0.2, L: 2.962 },
  sensitive: { lambda: 0.1, L: 2.814 },
} as const;

export interface EwmaPoint {
  t: number; // 1-based index in the series
  z: number;
  e: number;
  ucl: number;
  lcl: number;
  signal: boolean;
}

export interface EwmaResult {
  points: EwmaPoint[];
  /** 1-based index of first signal, or null */
  firstSignal: number | null;
  /** estimated sustained shift (mean z over last ceil(1/λ) points) at first signal, or null */
  shiftEstimate: number | null;
  lambda: number;
  L: number;
}

export function ewma(zs: readonly number[], opts: EwmaOptions = {}): EwmaResult {
  const lambda = opts.lambda ?? 0.2;
  const L = opts.L ?? 2.962;
  if (!(lambda > 0 && lambda <= 1)) throw new Error('lambda must be in (0, 1]');
  const asym = Math.sqrt(lambda / (2 - lambda));
  const points: EwmaPoint[] = [];
  let e = 0;
  let firstSignal: number | null = null;
  let shiftEstimate: number | null = null;
  for (let i = 0; i < zs.length; i++) {
    const t = i + 1;
    e = lambda * zs[i] + (1 - lambda) * e;
    const width = L * asym * Math.sqrt(1 - Math.pow(1 - lambda, 2 * t));
    const signal = Math.abs(e) > width;
    points.push({ t, z: zs[i], e, ucl: width, lcl: -width, signal });
    if (signal && firstSignal === null) {
      firstSignal = t;
      const k = Math.ceil(1 / lambda);
      const window = zs.slice(Math.max(0, i + 1 - k), i + 1);
      shiftEstimate = window.reduce((a, b) => a + b, 0) / window.length;
    }
  }
  return { points, firstSignal, shiftEstimate, lambda, L };
}

export interface VarianceEwmaPoint {
  t: number;
  z: number;
  v: number;
  ucl: number;
  signal: boolean;
}

export interface VarianceEwmaResult {
  points: VarianceEwmaPoint[];
  firstSignal: number | null;
  lambda: number;
  ucl: number;
}

/**
 * Monte-Carlo-calibrated upper limits for the variance EWMA at ARL0 ≈ 500
 * (asymptotic, in-control z ~ N(0,1)). Values generated by tools/reference
 * (see fixtures/variance_ewma_calibration.json) and mirrored here as defaults.
 * The asymptotic-theory limit 1 + L·sqrt(λ/(2−λ)·2) is a poor approximation because
 * z² is χ²₁ (skewed), hence the calibration.
 */
export const VARIANCE_EWMA_UCL: Record<string, number> = {
  '0.1': 2.085,
  '0.2': 2.927,
};

export function varianceEwma(
  zs: readonly number[],
  opts: { lambda?: number; ucl?: number } = {},
): VarianceEwmaResult {
  const lambda = opts.lambda ?? 0.2;
  const ucl = opts.ucl ?? VARIANCE_EWMA_UCL[String(lambda)] ?? 1 + 2.962 * Math.sqrt((lambda / (2 - lambda)) * 2);
  const points: VarianceEwmaPoint[] = [];
  let v = 1;
  let firstSignal: number | null = null;
  for (let i = 0; i < zs.length; i++) {
    const t = i + 1;
    v = lambda * zs[i] * zs[i] + (1 - lambda) * v;
    const signal = v > ucl;
    points.push({ t, z: zs[i], v, ucl, signal });
    if (signal && firstSignal === null) firstSignal = t;
  }
  return { points, firstSignal, lambda, ucl };
}
