/**
 * Report generation: daily QC, monthly summary, plate analysis. Print-optimized HTML
 * (A4) written to <dataDir>/reports; every generation is recorded in `report` and the
 * audit log. PDF, when needed, is produced by the user's browser print dialog or a
 * headless Chromium if `playwright-chromium` happens to be installed (optional).
 */
import type Database from 'better-sqlite3';
import { writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import { appendAudit, ulid } from '@sentinel/db';
import { ljChartSvg, heatmapSvg } from './svg.js';
import { ljData } from './charts.js';
import { runLog } from './runlog.js';
import { workspaceLab } from '../workspace.js';

const CSS = `
  @page { size: A4; margin: 14mm 13mm; }
  * { box-sizing: border-box; }
  body { font: 12px/1.5 -apple-system, 'Segoe UI', 'Inter', ui-sans-serif, sans-serif; color: #0f172a; margin: 0; background: #fff; }
  h1 { font-size: 17px; margin: 0 0 2px; } h2 { font-size: 13px; margin: 18px 0 6px; border-bottom: 1px solid #d1d5db; padding-bottom: 3px;}
  .meta { color: #64748b; font-size: 11px; margin-bottom: 14px; }
  table { border-collapse: collapse; width: 100%; margin: 6px 0 10px; }
  th, td { border: 1px solid #e2e8f0; padding: 4px 8px; text-align: left; font-size: 11px; }
  th { background: #f8fafc; font-weight: 600; color: #334155; }
  tbody tr:nth-child(even) td { background: #fafbfd; }
  td.num, .num { font-family: ui-monospace, 'SF Mono', 'JetBrains Mono', monospace; font-variant-numeric: tabular-nums; }
  td.num { text-align: right; }
  .pass { color: #16a34a; } .warning { color: #d97706; } .reject { color: #dc2626; font-weight: 600; }
  .signoff { margin-top: 28px; display: flex; gap: 40px; }
  .signoff div { border-top: 1px solid #374151; padding-top: 4px; width: 220px; font-size: 11px; color: #374151; }
  .finding { margin: 4px 0; padding: 6px 8px; border-left: 3px solid #dc2626; background: #fef2f2; font-size: 11px; }
  .note { color: #64748b; font-size: 10px; }
  footer { margin-top: 24px; font-size: 9.5px; color: #94a3b8; border-top: 1px solid #e2e8f0; padding-top: 5px; }

  /* card language for the QC report */
  .rcard { border: 1px solid #e2e8f0; border-radius: 10px; padding: 12px 16px; background: #fff; }
  .rgrid { display: flex; gap: 10px; }
  .rgrid > * { flex: 1; }
  .kicker { letter-spacing: 2.5px; font-size: 9.5px; color: #64748b; font-weight: 700; }
  .labname { font-size: 18px; font-weight: 700; margin: 3px 0 1px; letter-spacing: -0.2px; }
  .sub { color: #475569; font-size: 11.5px; }
  .status-card { border-radius: 10px; padding: 12px 18px; min-width: 200px; }
  .status-ok { border: 1px solid #bbf7d0; background: #f0fdf4; }
  .status-bad { border: 1px solid #fecaca; background: #fef2f2; }
  .status-title { font-size: 10.5px; font-weight: 700; color: #334155; }
  .status-word { font-size: 23px; font-weight: 800; letter-spacing: -0.3px; }
  .tile { border: 1px solid #e2e8f0; border-radius: 10px; padding: 10px 14px; }
  .tile .t-label { font-size: 10.5px; color: #64748b; font-weight: 600; }
  .tile .t-value { font-size: 19px; font-weight: 700; margin-top: 1px; }
  .limitbox { border: 1px solid #e2e8f0; border-radius: 8px; padding: 7px 10px; text-align: center; }
  .limitbox .l-label { font-size: 10px; color: #64748b; font-weight: 600; }
  .limitbox .l-value { font-size: 12.5px; font-weight: 700; margin-top: 1px; }
  .limitbox.mean { border-color: #cbd5e1; background: #f8fafc; }
  .section-title { font-size: 14px; font-weight: 700; margin: 20px 0 1px; letter-spacing: -0.2px; }
  .section-sub { color: #64748b; font-size: 11px; margin: 0 0 8px; }
  .chartwrap { border: 1px solid #e2e8f0; border-radius: 10px; padding: 10px 6px 4px; }
  .flag { display: inline-block; border-radius: 5px; padding: 0 5px; font-size: 10px; font-weight: 600; }
  .flag-warn { background: #fef3c7; color: #b45309; }
  .flag-rej { background: #fee2e2; color: #b91c1c; }
  .ok-badge { color: #16a34a; font-weight: 700; font-size: 10.5px; }
  .runlog-table td, .runlog-table th { border-left: none; border-right: none; }
  .runlog-table th { background: #fff; border-bottom: 1.5px solid #cbd5e1; text-transform: uppercase; font-size: 9.5px; letter-spacing: 0.8px; }
  .avoid-break { break-inside: avoid; }
`;

function esc(s: unknown): string {
  return String(s ?? '').replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' })[c]!);
}

function page(title: string, body: string, generatedBy: string): string {
  return `<!-- Sentinel QC report -->
<meta charset="utf-8">
<title>${esc(title)}</title>
<style>${CSS}</style>
<h1>${esc(title)}</h1>
${body}
<footer>Generated by ${esc(generatedBy)} · ${new Date().toISOString()} · Sentinel QC. This document supports internal quality management; it is not a compliance certificate.</footer>`;
}

function saveReport(
  sqlite: Database.Database,
  dataDir: string,
  kind: string,
  params: unknown,
  html: string,
  userId: string,
  workspaceId: string,
): { id: string; filePath: string } {
  const dir = join(dataDir, 'reports');
  mkdirSync(dir, { recursive: true, mode: 0o700 });
  const id = ulid();
  const filePath = join(dir, `${kind}-${id}.html`);
  writeFileSync(filePath, html, { mode: 0o600 });
  sqlite
    .prepare('INSERT INTO report (id, kind, params_json, generated_at, generated_by, file_path, workspace_id) VALUES (?, ?, ?, ?, ?, ?, ?)')
    .run(id, kind, JSON.stringify(params), new Date().toISOString(), userId, filePath, workspaceId);
  appendAudit(sqlite, { userId, entity: 'report', entityId: id, action: 'generate_report', after: { kind, params } });
  return { id, filePath };
}

export function dailyReport(sqlite: Database.Database, dataDir: string, date: string, userId: string, workspaceId: string) {
  const user = sqlite.prepare('SELECT display_name FROM user WHERE id = ?').get(userId) as { display_name: string };
  const lab = workspaceLab(sqlite, workspaceId);
  const runs = sqlite
    .prepare(
      `SELECT r.*, a.name as assay_name, a.units, u.display_name as operator, i.label as instrument, rl.lot as reagent_lot
       FROM run r
       JOIN assay a ON a.id = r.assay_id
       JOIN user u ON u.id = r.operator_user_id
       LEFT JOIN instrument i ON i.id = r.instrument_id
       LEFT JOIN reagent_lot rl ON rl.id = r.reagent_lot_id
       WHERE date(r.performed_at) = ? AND a.workspace_id = ?
       ORDER BY a.name, r.performed_at`,
    )
    .all(date, workspaceId) as Record<string, unknown>[];
  let body = `<div class="meta">${esc(lab?.name ?? 'Laboratory')} · Daily QC report for ${esc(date)}</div>`;
  if (runs.length === 0) body += `<p>No QC runs were recorded on this date.</p>`;
  const byAssay = new Map<string, Record<string, unknown>[]>();
  for (const r of runs) {
    const list = byAssay.get(r.assay_name as string) ?? [];
    list.push(r);
    byAssay.set(r.assay_name as string, list);
  }
  for (const [assayName, assayRuns] of byAssay) {
    body += `<h2>${esc(assayName)}</h2><table><tr><th>Time</th><th>Level</th><th>Value</th><th>z</th><th>Verdict</th><th>Rules</th><th>Operator</th><th>Instrument</th><th>Reagent lot</th></tr>`;
    for (const r of assayRuns) {
      const obs = sqlite
        .prepare(
          `SELECT m.level_code, o.raw_value, o.z FROM observation o JOIN qc_material m ON m.id = o.qc_material_id
           WHERE o.run_id = ? AND o.superseded = 0 ORDER BY m.level_code, o.replicate_index`,
        )
        .all(r.id) as { level_code: string; raw_value: number; z: number | null }[];
      const rules = sqlite
        .prepare(`SELECT rule FROM rule_evaluation WHERE run_id = ? AND status IN ('warning','reject')`)
        .all(r.id) as { rule: string }[];
      obs.forEach((o, idx) => {
        body += `<tr>
          ${idx === 0 ? `<td rowspan="${obs.length}">${esc((r.performed_at as string).slice(11, 16))}</td>` : ''}
          <td>${esc(o.level_code)}</td>
          <td class="num">${o.raw_value.toFixed(3)}</td>
          <td class="num">${o.z === null ? '—' : o.z.toFixed(2)}</td>
          ${idx === 0 ? `<td rowspan="${obs.length}" class="${r.verdict}">${esc((r.verdict as string).toUpperCase())}${r.override_status === 'accepted' ? ' (accepted)' : ''}</td>` : ''}
          ${idx === 0 ? `<td rowspan="${obs.length}">${esc(rules.map((x) => x.rule).join(', ') || '—')}</td>` : ''}
          ${idx === 0 ? `<td rowspan="${obs.length}">${esc(r.operator)}</td>` : ''}
          ${idx === 0 ? `<td rowspan="${obs.length}">${esc(r.instrument ?? '—')}</td>` : ''}
          ${idx === 0 ? `<td rowspan="${obs.length}">${esc(r.reagent_lot ?? '—')}</td>` : ''}
        </tr>`;
      });
    }
    body += `</table>`;
  }
  body += `<div class="signoff"><div>Reviewed by (supervisor)</div><div>Date</div></div>`;
  const html = page(`Daily QC report — ${date}`, body, user.display_name);
  return saveReport(sqlite, dataDir, 'daily', { date }, html, userId, workspaceId);
}

export function monthlyReport(sqlite: Database.Database, dataDir: string, month: string, userId: string, workspaceId: string) {
  const user = sqlite.prepare('SELECT display_name FROM user WHERE id = ?').get(userId) as { display_name: string };
  const lab = workspaceLab(sqlite, workspaceId);
  const from = `${month}-01T00:00:00Z`;
  const toDate = new Date(new Date(from).getFullYear(), new Date(from).getMonth() + 1, 1);
  const to = toDate.toISOString();
  const assays = sqlite.prepare('SELECT * FROM assay WHERE active = 1 AND workspace_id = ? ORDER BY name').all(workspaceId) as Record<string, unknown>[];
  let body = `<div class="meta">${esc(lab?.name ?? 'Laboratory')} · Monthly QC summary for ${esc(month)}</div>`;
  for (const a of assays) {
    const scheme = JSON.parse(a.qc_scheme_json as string) as { levels: { level_code: string }[] };
    for (const lvl of scheme.levels) {
      const data = ljData(sqlite, a.id as string, lvl.level_code, from, to);
      if (!data.ok || data.points.length === 0) continue;
      body += `<h2>${esc(a.name)} — level ${esc(lvl.level_code)}</h2>`;
      body += ljChartSvg(data.points.map((p) => ({ z: p.z, violated: p.violatedRules.length > 0 })));
      const s = data.stats;
      const failures = new Map<string, number>();
      for (const p of data.points) for (const r of p.violatedRules) failures.set(r, (failures.get(r) ?? 0) + 1);
      body += `<table><tr><th>n</th><th>Mean (transformed)</th><th>SD</th><th>CV%</th><th>Baseline</th><th>Failures by rule</th></tr>
        <tr><td class="num">${s.n}</td><td class="num">${s.mean?.toFixed(4) ?? '—'}</td><td class="num">${s.sd?.toFixed(4) ?? '—'}</td>
        <td class="num">${s.cv?.toFixed(1) ?? '—'}</td>
        <td>${data.baseline ? `${esc(data.baseline.method)} (n=${data.baseline.n}, frozen)` : 'none'}</td>
        <td>${esc(Array.from(failures.entries()).map(([r, c]) => `${r}: ${c}`).join(', ') || 'none')}</td></tr></table>`;
      const events = data.events.filter((e) => e.kind !== 'instrument');
      if (events.length > 0) {
        body += `<p class="note">Events: ${esc(events.map((e) => `${e.performedAt.slice(0, 10)} ${e.label}`).join(' · '))}</p>`;
      }
      const signals = sqlite
        .prepare(
          `SELECT s.monitor, s.message, r.performed_at FROM monitor_signal s LEFT JOIN run r ON r.id = s.run_id
           WHERE s.assay_id = ? AND r.performed_at >= ? AND r.performed_at < ?`,
        )
        .all(a.id, from, to) as { monitor: string; message: string; performed_at: string }[];
      for (const sig of signals) {
        body += `<p class="note">[${esc(sig.monitor)}] ${esc(sig.message)}</p>`;
      }
    }
  }
  body += `<div class="signoff"><div>Reviewed by (supervisor)</div><div>Date</div></div>`;
  const html = page(`Monthly QC summary — ${month}`, body, user.display_name);
  return saveReport(sqlite, dataDir, 'monthly', { month }, html, userId, workspaceId);
}

const RULE_LEGEND: [string, string][] = [
  ['1_2s', 'one control beyond ±2SD (warning — triggers inspection, not rejection)'],
  ['1_3s', 'one control beyond ±3SD (random error)'],
  ['2_2s', 'two consecutive controls beyond the same ±2SD limit (systematic error)'],
  ['R_4s', 'controls on opposite sides beyond ±2SD within a run (random error)'],
  ['4_1s', 'four consecutive controls beyond ±1SD on the same side'],
  ['10x', 'ten consecutive controls on the same side of the mean'],
  ['2of3_2s', 'two of three controls beyond the same ±2SD limit'],
  ['3_1s', 'three consecutive controls beyond ±1SD on the same side'],
  ['6x', 'six consecutive controls on the same side of the mean'],
];

/**
 * The QC report — modelled on the report labs already file (status card, tiles,
 * LJ chart with band values, control-limits strip, newest-first run log, sign-off),
 * with per-run rule flags named, a rule legend, and the limits source stated.
 */
export function assayReport(
  sqlite: Database.Database,
  dataDir: string,
  assayId: string,
  userId: string,
  workspaceId: string,
  from?: string,
  to?: string,
) {
  const user = sqlite.prepare('SELECT display_name FROM user WHERE id = ?').get(userId) as { display_name: string };
  const lab = workspaceLab(sqlite, workspaceId);
  const assay = sqlite.prepare('SELECT * FROM assay WHERE id = ?').get(assayId) as Record<string, unknown> | undefined;
  if (!assay) return null;
  const scheme = JSON.parse(assay.qc_scheme_json as string) as { levels: { level_code: string }[] };

  const logs = scheme.levels
    .map((lvl) => runLog(sqlite, assayId, lvl.level_code, from, to))
    .filter((l) => l.ok && (l.rows?.length ?? 0) > 0);
  const allRows = logs.flatMap((l) => l.rows ?? []);
  const dates = allRows.map((r) => r.performedAt.slice(0, 10)).sort();
  const period =
    from || to
      ? `${from ? from.slice(0, 10) : 'start'} to ${to ? to.slice(0, 10) : 'today'}`
      : dates.length > 0
        ? `${dates[0]} to ${dates[dates.length - 1]}`
        : '—';
  const inControl = logs.every((l) => l.status!.inControl);
  const totalRejects = logs.reduce((a, l) => a + l.status!.rejects, 0);
  const totalWarnings = logs.reduce((a, l) => a + l.status!.warnings, 0);
  const statusMessage = inControl
    ? totalWarnings === 0
      ? 'No rule violations detected'
      : `${totalWarnings} warning${totalWarnings === 1 ? '' : 's'} (1_2s); no rejection rule fired`
    : `${totalRejects} run${totalRejects === 1 ? '' : 's'} violate${totalRejects === 1 ? 's' : ''} rejection rules`;

  // ---- header: report identity + status card
  let body = `
  <div class="rgrid avoid-break" style="margin-bottom:12px; align-items:stretch;">
    <div class="rcard" style="flex:2.2;">
      <div class="kicker">QC REPORT</div>
      <div class="labname">${esc(lab?.name ?? 'Laboratory')}</div>
      <div class="sub">${esc(assay.name)} · ${esc(assay.methodology)}${scheme.levels.length === 1 ? ` · ${esc(scheme.levels[0].level_code)}` : ''}</div>
      <div class="sub">Date range: <span class="num">${esc(period)}</span></div>
    </div>
    <div class="status-card ${inControl ? 'status-ok' : 'status-bad'}" style="flex:1;">
      <div class="status-title">Final Status</div>
      <div class="status-word" style="color:${inControl ? '#16a34a' : '#dc2626'};">${inControl ? 'In Control' : 'Out of Control'}</div>
      <div class="note">${esc(statusMessage)}</div>
    </div>
  </div>`;

  for (const log of logs) {
    const lim = log.limits;
    const st = log.stats!;
    const isRatio = log.valueLabel === 'E-ratio';
    if (logs.length > 1) body += `<div class="section-title">Level ${esc(log.levelCode!)}</div>`;

    // ---- tiles
    body += `<div class="rgrid avoid-break" style="margin-bottom:14px;">
      ${[
        ['Runs', String(st.n)],
        [`Mean ${log.valueLabel!}`, st.mean?.toFixed(3) ?? '—'],
        ['SD', st.sd?.toFixed(3) ?? '—'],
        ['CV%', st.cv !== null ? `${st.cv!.toFixed(2)}%` : '—'],
      ]
        .map(([label, value]) => `<div class="tile"><div class="t-label">${esc(label)}</div><div class="t-value num">${esc(value)}</div></div>`)
        .join('')}
    </div>`;

    // ---- chart
    body += `<div class="avoid-break"><div class="section-title">Levey–Jennings Chart</div>
      <p class="section-sub">${esc(log.valueLabel!)} vs control bands.</p>
      <div class="chartwrap">${ljChartSvg(
        (log.series ?? []).map((p) => ({ z: p.z, violated: p.flags.some((f) => f !== '1_2s') })),
        740,
        240,
        lim?.bands,
      )}</div></div>`;

    // ---- control limits
    if (lim) {
      body += `<div class="avoid-break"><div class="section-title">Control Limits</div>
        <p class="section-sub">${
          lim.source === 'self'
            ? `Using mean and SD calculated from the current runs${(lim.excluded ?? 0) > 0 ? ` — ${lim.excluded} gross outlier${lim.excluded === 1 ? '' : 's'} excluded from the estimate by robust screen (still shown and flagged)` : ''}.`
            : `Using the laboratory's frozen baseline (${esc(lim.baselineMethod ?? '')}${lim.n ? `, n=${lim.n}` : ''}).`
        }</p>
        <div class="rgrid">
          ${(
            [
              ['+3SD', lim.bands.p3],
              ['+2SD', lim.bands.p2],
              ['+1SD', lim.bands.p1],
              ['Mean', lim.bands.mean],
              ['−1SD', lim.bands.m1],
              ['−2SD', lim.bands.m2],
              ['−3SD', lim.bands.m3],
            ] as [string, number][]
          )
            .map(
              ([label, v]) =>
                `<div class="limitbox${label === 'Mean' ? ' mean' : ''}"><div class="l-label">${label}</div><div class="l-value num">${v.toFixed(3)}</div></div>`,
            )
            .join('')}
        </div></div>`;
    }

    // ---- run log (newest first)
    body += `<div class="section-title">QC Run Log</div>
      <p class="section-sub">${isRatio ? 'Calculated E-ratio and rule flags for each run.' : 'Values and rule flags for each run.'}</p>`;
    body += `<table class="runlog-table"><thead><tr><th>Run</th><th>Date</th><th>Technician</th><th>Kit lot</th>${
      isRatio ? '<th style="text-align:right;">IQC OD</th><th style="text-align:right;">Cutoff OD</th><th style="text-align:right;">E-ratio</th>' : `<th style="text-align:right;">Value (${esc(log.valueLabel!)})</th><th style="text-align:right;">z</th>`
    }<th>Flags</th></tr></thead><tbody>`;
    for (const r of log.rows!) {
      const flagsHtml =
        r.flags.length === 0
          ? `<span class="ok-badge">OK</span>`
          : r.flags
              .map((f) => `<span class="flag ${f === '1_2s' ? 'flag-warn' : 'flag-rej'}">${esc(f)}</span>`)
              .join(' ') + (r.overrideStatus === 'accepted' ? ' <span class="note">(accepted)</span>' : '');
      body += `<tr><td class="num" style="color:#64748b;">${r.runNo}</td><td class="num">${esc(r.performedAt.slice(0, 10))}</td>
        <td>${esc(r.technician ?? '—')}</td><td class="num">${esc(r.kitLot ?? '—')}</td>${
          isRatio
            ? `<td class="num">${r.raw.toFixed(3)}</td><td class="num">${r.cutoff?.toFixed(3) ?? '—'}</td><td class="num"><b>${r.value.toFixed(3)}</b></td>`
            : `<td class="num">${r.raw.toFixed(3)}</td><td class="num">${r.z?.toFixed(2) ?? '—'}</td>`
        }<td>${flagsHtml}</td></tr>`;
    }
    body += `</tbody></table>`;
  }

  if (logs.length === 0) body += `<p>No runs in the selected period.</p>`;

  // ---- rule legend (rules that appear, plus the two everyone asks about)
  const firedRules = new Set(allRows.flatMap((r) => r.flags));
  const legend = RULE_LEGEND.filter(([r]) =>
    firedRules.size === 0 ? ['1_2s', '1_3s', '2_2s', 'R_4s', '4_1s', '10x'].includes(r) : firedRules.has(r) || ['1_2s', '1_3s'].includes(r),
  );
  body += `<p class="note" style="margin-top:10px;">Westgard rules: ${legend.map(([r, d]) => `<b>${r}</b> — ${esc(d)}`).join('; ')}.</p>`;

  // ---- sign-off
  body += `<div class="rcard avoid-break" style="margin-top:16px;">
    <div class="rgrid">
      <div><div class="t-label" style="font-size:10.5px; color:#64748b; font-weight:600;">Prepared by</div>
        <div style="font-weight:700; margin-top:4px;">${esc(user.display_name)}</div></div>
      <div><div class="t-label" style="font-size:10.5px; color:#64748b; font-weight:600;">Generated on</div>
        <div class="num" style="font-weight:700; margin-top:4px;">${new Date().toISOString().slice(0, 10)}</div></div>
      <div><div class="t-label" style="font-size:10.5px; color:#64748b; font-weight:600;">Signature</div>
        <div style="border-bottom:1px solid #334155; height:26px; width:100%;"></div></div>
    </div>
  </div>`;

  const html = page(`QC Report — ${assay.name}`, body, user.display_name);
  return saveReport(sqlite, dataDir, 'assay', { assayId, from, to }, html, userId, workspaceId);
}

export function plateReport(sqlite: Database.Database, dataDir: string, plateId: string, userId: string, workspaceId: string) {
  const user = sqlite.prepare('SELECT display_name FROM user WHERE id = ?').get(userId) as { display_name: string };
  const plate = sqlite
    .prepare(`SELECT p.*, a.name as assay_name FROM plate p JOIN assay a ON a.id = p.assay_id WHERE p.id = ?`)
    .get(plateId) as Record<string, unknown> | undefined;
  if (!plate) return null;
  const analysis = sqlite
    .prepare('SELECT * FROM plate_analysis WHERE plate_id = ? ORDER BY analyzed_at DESC LIMIT 1')
    .get(plateId) as Record<string, unknown> | undefined;
  const wells = sqlite
    .prepare('SELECT row, col, transformed_value, residual FROM well_measurement WHERE plate_id = ?')
    .all(plateId) as { row: number; col: number; transformed_value: number | null; residual: number | null }[];
  const R = plate.rows as number;
  const C = plate.cols as number;
  const tGrid: (number | null)[][] = Array.from({ length: R }, () => new Array(C).fill(null));
  const rGrid: (number | null)[][] = Array.from({ length: R }, () => new Array(C).fill(null));
  for (const w of wells) {
    tGrid[w.row][w.col] = w.transformed_value;
    rGrid[w.row][w.col] = w.residual;
  }
  const findings = analysis ? (JSON.parse(analysis.findings_json as string) as { kind: string; message: string }[]) : [];
  let body = `<div class="meta">${esc(plate.assay_name)} · file ${esc(plate.source_filename)} · imported ${esc((plate.imported_at as string).slice(0, 16))} · transform: ${esc(plate.transform_used)}</div>`;
  body += `<h2>Transformed values</h2>${heatmapSvg(tGrid)}`;
  body += `<h2>Median-polish residuals</h2>${heatmapSvg(rGrid, { center: 0 })}`;
  body += `<h2>Findings</h2>`;
  const spatial = findings.filter((f) => f.kind !== 'local_outlier');
  if (spatial.length === 0) body += `<p>No spatially structured artifacts were detected.</p>`;
  for (const f of findings) body += `<div class="finding">${esc(f.message)}</div>`;
  if (analysis?.t2 !== null && analysis?.t2 !== undefined) {
    body += `<h2>Phase-II monitoring</h2><table><tr><th>T²</th><th>SPE</th></tr><tr><td class="num">${(analysis.t2 as number).toFixed(2)}</td><td class="num">${(analysis.spe as number).toFixed(2)}</td></tr></table>`;
  }
  const html = page(`Plate analysis — ${plate.source_filename}`, body, user.display_name);
  return saveReport(sqlite, dataDir, 'plate', { plateId }, html, userId, workspaceId);
}
